version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      dotnet: 2.1
    commands:
      - yarn --version
      - yarn global add serverless
      - npm install --save-dev serverless-step-functions
      - serverless -v 
  build:
    commands:
      - dotnet restore
      - dotnet lambda package --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/deploy-package.zip
      - serverless deploy --stage $target 